# security.jwt.token.secret-key: my-secret-key
#
# spring:
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5431/wsebanking
#     username: willsedgar
#     password: 2123
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     hibernate:
#       ddl-auto: validate
#

security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres  # Supabase database URL
    username: postgres.ixpgspabkcfkjlewsetu  # Supabase username
    password: vkfaU6wLrKJNa3 # Supabase password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.ixpgspabkcfkjlewsetu&password=[YOUR-PASSWORD]
