name: Spring Boot Test


on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.2

    - name: Navigate to the Spring Boot project directory
      run: cd Backend/WSEBanking
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'oracle'
      
    - name: Build with Maven
      run: mvn -B clean install

    - name: Test with Maven
      run: mvn test
      
   
  
