name: Spring Boot Test


on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        
  
    - name: Build with Maven
      run: mvn -B clean package

    - name: Test with Maven
      run: mvn test
      
   
  
