name: Spring Boot Test


on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: action/checkout@v3

    - name: Navigate to the Spring Boot project directory
      run: cd Backend/WSEBanking
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
      
    - name: Build with Maven
      run: mvn -B clean install

    - name: Test with Maven
      run: mvn test
      
   
  
